---
# This Docker composition file is used to build and test the container

name: skeleton-docker

services:
  vdp-scanner:
    # Run the container normally
    build:
      context: .
      dockerfile: Dockerfile
    image: cisagov/vdp-scanner
    init: true
    restart: "no"
    volumes:
      - .:/task/host_mount

  vdp-scanner-version:
    # Run the container to collect version information
    command: --version
    image: cisagov/vdp-scanner
    init: true
    restart: "no"
