---
version: "3.7"

# This docker-compose file is used to build and test the container

services:
  vdp-scanner:
    # Run the container normally
    build:
      # SERVERLESS_CHROME_VERSION and SERVERLESS_CHROME_LOCAL can be specified
      # on the command line to modify what is installed and where:
      # --build-arg SERVERLESS_CHROME_VERSION=v1.0.0-56
      # --build-arg SERVERLESS_CHROME_LOCAL=/opt/serverless-chrome
      context: .
      dockerfile: Dockerfile
    image: cisagov/vdp-scanner
    init: true
    restart: "no"
    user: "${UID}:${GID}"
    volumes:
      - .:/home/cisa/host_mount

  vdp-scanner-version:
    # Run the container to collect version information
    image: cisagov/vdp-scanner
    init: true
    restart: "no"
    command: --version
