---
version: "3.7"

# This docker-compose file is used to build and test the container

services:
  vdp-scanner:
    # Run the container normally
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    image: cisagov/vdp-scanner
    init: true
    restart: "no"

  vdp-scanner-version:
    # Run the container to collect version information
    image: cisagov/vdp-scanner
    init: true
    restart: "no"
    command: --version
